//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_shop
{
    using System;
    using System.Collections.Generic;
    

    public partial class Clients
    {
        public Clients(string email, string firstname, string lastname, string adress, string phone_nubmer, string pasword)
        {
            this.email = email;
            this.firstname = firstname;
            this.lastname = lastname;
            this.adress = adress;
            this.phone_nubmer = phone_nubmer;
            this.pasword = pasword;
        }

        public int id_client { get; set; }
        public string email { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string adress { get; set; }
        public string phone_nubmer { get; set; }
        public string pasword { get; set; }
    }
}
