//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int Comment_id { get; set; }
        public Nullable<int> Comment_product_id { get; set; }
        public Nullable<int> Comment_user_id { get; set; }
        public string comment { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
