//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int details_id { get; set; }
        public Nullable<int> detail_order_id { get; set; }
        public Nullable<int> details_product_id { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
