//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows.Media.Imaging;
using Sushi_shop.Annotations;
using Sushi_shop.converter;

namespace Sushi_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.comments = new HashSet<comments>();
            this.order_details = new HashSet<order_details>();
        }

        private BitmapImage _product_bitmap;
        private byte[] _product_image;
        public int id_product { get; set; }
        private string _product_name { get; set; }
        private int _product_quantity ;
        private double _price { get; set; }
        public Nullable<int> category_id { get; set; }
        private category _category { get; set; }

        public virtual category category
        {
            get => _category;
            set
            {
                _category= value;
                OnPropertyChanged("category");
            }
        }

        public string product_name
        {
            get => _product_name;
            set
            {
                _product_name = value;
                OnPropertyChanged("product_name");
            }
        }
        public double price
        {
            get => _price;
            set
            {
                _price = value;
                OnPropertyChanged("price");
            }
        }
        public int product_quantity
        {
            get => _product_quantity;
            set
            {
                _product_quantity = value;
                OnPropertyChanged("product_quantity");
            }
        }

        public byte[] product_image
        {
            get => _product_image;
            set
            {
                _product_image = value;
                OnPropertyChanged("product_bitmap");
            }
        }

        public BitmapImage product_bitmap
        {
            get{ return BinaryToBitmap.ByteToBitmapImage(_product_image); }
            set
            {
                _product_bitmap = BinaryToBitmap.ByteToBitmapImage(_product_image);
                OnPropertyChanged("product_bitmap");
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
